# Generated by Django 6.0.6 on 2026-06-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=20)),
                ('leetcode_link', models.URLField()),
                ('logic_notes', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('need_revision', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.topic')),
            ],
        ),
    ]
